/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgingBucket {
  'count' : bigint,
  'totalAmount' : bigint,
  'bucket' : string,
}
export type AssignmentId = bigint;
export interface CollectionSummary {
  'totalOverdue' : bigint,
  'totalCollected' : bigint,
  'totalOutstanding' : bigint,
  'totalWaived' : bigint,
  'paymentCount' : bigint,
}
export interface CreateFeeStructureInput {
  'endDate' : Timestamp,
  'period' : FeePeriod,
  'name' : string,
  'latePenalty' : [] | [LatePenalty],
  'dueDate' : Timestamp,
  'description' : string,
  'amount' : bigint,
  'startDate' : Timestamp,
}
export interface CreateStudentInput {
  'studentId' : string,
  'name' : string,
  'email' : string,
  'group' : string,
}
export interface CsvStudentRow {
  'studentId' : string,
  'name' : string,
  'email' : string,
  'group' : string,
}
export interface FeeAssignment {
  'id' : AssignmentId,
  'status' : PaymentStatus,
  'studentId' : StudentId,
  'feeStructureId' : FeeStructureId,
  'assignedAt' : Timestamp,
  'waivedReason' : [] | [string],
  'updatedAt' : Timestamp,
}
export type FeePeriod = { 'semester' : null } |
  { 'term' : null } |
  { 'annual' : null } |
  { 'monthly' : null };
export interface FeeStructure {
  'id' : FeeStructureId,
  'endDate' : Timestamp,
  'period' : FeePeriod,
  'name' : string,
  'createdAt' : Timestamp,
  'latePenalty' : [] | [LatePenalty],
  'dueDate' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'amount' : bigint,
  'startDate' : Timestamp,
}
export type FeeStructureId = bigint;
export type LatePenalty = { 'fixed' : bigint } |
  { 'percentage' : bigint };
export interface Payment {
  'id' : PaymentId,
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'feeStructureId' : FeeStructureId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : string,
  'amount' : bigint,
  'receiptNumber' : string,
}
export type PaymentId = bigint;
export type PaymentMethod = { 'cash' : null } |
  { 'check' : null } |
  { 'transfer' : null } |
  { 'online' : null };
export interface PaymentMethodBreakdown {
  'cash' : bigint,
  'check' : bigint,
  'transfer' : bigint,
  'online' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null } |
  { 'waived' : null } |
  { 'partial' : null };
export interface RecordPaymentInput {
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'feeStructureId' : FeeStructureId,
  'date' : Timestamp,
  'notes' : string,
  'amount' : bigint,
  'receiptNumber' : string,
}
export interface Student {
  'id' : StudentId,
  'studentId' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'updatedAt' : Timestamp,
  'group' : string,
}
export interface StudentBalance {
  'status' : PaymentStatus,
  'feeStructureName' : string,
  'studentId' : StudentId,
  'feeStructureId' : FeeStructureId,
  'studentName' : string,
  'dueDate' : Timestamp,
  'totalAmount' : bigint,
  'outstandingAmount' : bigint,
  'paidAmount' : bigint,
}
export type StudentId = bigint;
export type Timestamp = bigint;
export interface UpdateFeeStructureInput {
  'id' : FeeStructureId,
  'endDate' : Timestamp,
  'period' : FeePeriod,
  'name' : string,
  'latePenalty' : [] | [LatePenalty],
  'dueDate' : Timestamp,
  'description' : string,
  'amount' : bigint,
  'startDate' : Timestamp,
}
export interface UpdateStudentInput {
  'id' : StudentId,
  'studentId' : string,
  'name' : string,
  'email' : string,
  'group' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignFeeToGroup' : ActorMethod<
    [string, FeeStructureId],
    Array<FeeAssignment>
  >,
  'assignFeeToStudent' : ActorMethod<
    [StudentId, FeeStructureId],
    FeeAssignment
  >,
  'bulkImportStudents' : ActorMethod<[Array<CsvStudentRow>], Array<Student>>,
  'createFeeStructure' : ActorMethod<[CreateFeeStructureInput], FeeStructure>,
  'createStudent' : ActorMethod<[CreateStudentInput], Student>,
  'deleteFeeStructure' : ActorMethod<[FeeStructureId], boolean>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'duplicateFeeStructure' : ActorMethod<[FeeStructureId], [] | [FeeStructure]>,
  'getAgingReport' : ActorMethod<[], Array<AgingBucket>>,
  'getAllBalances' : ActorMethod<[], Array<StudentBalance>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectionSummary' : ActorMethod<[], CollectionSummary>,
  'getFeeStructure' : ActorMethod<[FeeStructureId], [] | [FeeStructure]>,
  'getFeeStructureBalances' : ActorMethod<
    [FeeStructureId],
    Array<StudentBalance>
  >,
  'getPaymentMethodBreakdown' : ActorMethod<[], PaymentMethodBreakdown>,
  'getPaymentsByDateRange' : ActorMethod<
    [Timestamp, Timestamp],
    Array<Payment>
  >,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentBalances' : ActorMethod<[StudentId], Array<StudentBalance>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFeeStructures' : ActorMethod<[], Array<FeeStructure>>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listStudentsByGroup' : ActorMethod<[string], Array<Student>>,
  'recordPayment' : ActorMethod<[RecordPaymentInput], Payment>,
  'unenrollStudent' : ActorMethod<[StudentId, FeeStructureId], boolean>,
  'updateFeeStructure' : ActorMethod<
    [UpdateFeeStructureInput],
    [] | [FeeStructure]
  >,
  'updateOverdueStatuses' : ActorMethod<[], undefined>,
  'updateStudent' : ActorMethod<[UpdateStudentInput], [] | [Student]>,
  'waiveFee' : ActorMethod<
    [StudentId, FeeStructureId, string],
    [] | [FeeAssignment]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];