/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FeeStructureId = IDL.Nat;
export const AssignmentId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
  'waived' : IDL.Null,
  'partial' : IDL.Null,
});
export const StudentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const FeeAssignment = IDL.Record({
  'id' : AssignmentId,
  'status' : PaymentStatus,
  'studentId' : StudentId,
  'feeStructureId' : FeeStructureId,
  'assignedAt' : Timestamp,
  'waivedReason' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
});
export const CsvStudentRow = IDL.Record({
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'group' : IDL.Text,
});
export const ImportRowError = IDL.Record({
  'row' : IDL.Nat,
  'field' : IDL.Text,
  'value' : IDL.Text,
  'message' : IDL.Text,
});
export const ImportResult = IDL.Record({
  'imported' : IDL.Nat,
  'errors' : IDL.Vec(ImportRowError),
});
export const FeePeriod = IDL.Variant({
  'semester' : IDL.Null,
  'term' : IDL.Null,
  'annual' : IDL.Null,
  'monthly' : IDL.Null,
});
export const LatePenalty = IDL.Variant({
  'fixed' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const CreateFeeStructureInput = IDL.Record({
  'endDate' : Timestamp,
  'period' : FeePeriod,
  'name' : IDL.Text,
  'latePenalty' : IDL.Opt(LatePenalty),
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
  'startDate' : Timestamp,
});
export const FeeStructure = IDL.Record({
  'id' : FeeStructureId,
  'endDate' : Timestamp,
  'period' : FeePeriod,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'latePenalty' : IDL.Opt(LatePenalty),
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'amount' : IDL.Nat,
  'startDate' : Timestamp,
});
export const CreateStudentInput = IDL.Record({
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'group' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'group' : IDL.Text,
});
export const AgingBucket = IDL.Record({
  'count' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'bucket' : IDL.Text,
});
export const AgingBucketDetail = IDL.Record({
  'daysOverdue' : IDL.Nat,
  'feeStructureName' : IDL.Text,
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'amountPaid' : IDL.Nat,
  'amountDue' : IDL.Nat,
});
export const StudentBalance = IDL.Record({
  'status' : PaymentStatus,
  'feeStructureName' : IDL.Text,
  'studentId' : StudentId,
  'feeStructureId' : FeeStructureId,
  'studentName' : IDL.Text,
  'penaltyAmount' : IDL.Nat,
  'dueDate' : Timestamp,
  'totalAmount' : IDL.Nat,
  'outstandingAmount' : IDL.Nat,
  'totalWithPenalty' : IDL.Nat,
  'paidAmount' : IDL.Nat,
});
export const CollectionSummary = IDL.Record({
  'totalOverdue' : IDL.Nat,
  'totalCollected' : IDL.Nat,
  'totalOutstanding' : IDL.Nat,
  'totalWaived' : IDL.Nat,
  'totalOutstandingWithPenalty' : IDL.Nat,
  'paymentCount' : IDL.Nat,
});
export const CollectionTrends = IDL.Record({
  'previousPeriodTotal' : IDL.Nat,
  'previousPeriodCount' : IDL.Nat,
  'currentPeriodTotal' : IDL.Nat,
  'currentPeriodCount' : IDL.Nat,
});
export const PaymentMethodBreakdown = IDL.Record({
  'cash' : IDL.Nat,
  'check' : IDL.Nat,
  'transfer' : IDL.Nat,
  'online' : IDL.Nat,
});
export const PaymentId = IDL.Nat;
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'check' : IDL.Null,
  'transfer' : IDL.Null,
  'online' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'feeStructureId' : FeeStructureId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const RecordPaymentInput = IDL.Record({
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'feeStructureId' : FeeStructureId,
  'date' : Timestamp,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const RecordPaymentError = IDL.Variant({
  'DuplicateReceipt' : IDL.Null,
  'NotFound' : IDL.Null,
});
export const UpdateFeeStructureInput = IDL.Record({
  'id' : FeeStructureId,
  'endDate' : Timestamp,
  'period' : FeePeriod,
  'name' : IDL.Text,
  'latePenalty' : IDL.Opt(LatePenalty),
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
  'startDate' : Timestamp,
});
export const UpdateStudentInput = IDL.Record({
  'id' : StudentId,
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'group' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignFeeToGroup' : IDL.Func(
      [IDL.Text, FeeStructureId],
      [IDL.Vec(FeeAssignment)],
      [],
    ),
  'assignFeeToStudent' : IDL.Func(
      [StudentId, FeeStructureId],
      [FeeAssignment],
      [],
    ),
  'bulkImportStudents' : IDL.Func([IDL.Vec(CsvStudentRow)], [ImportResult], []),
  'checkReceiptExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createFeeStructure' : IDL.Func(
      [CreateFeeStructureInput],
      [FeeStructure],
      [],
    ),
  'createStudent' : IDL.Func([CreateStudentInput], [Student], []),
  'deleteFeeStructure' : IDL.Func([FeeStructureId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'duplicateFeeStructure' : IDL.Func(
      [FeeStructureId],
      [IDL.Opt(FeeStructure)],
      [],
    ),
  'getAgingReport' : IDL.Func([], [IDL.Vec(AgingBucket)], []),
  'getAgingReportDetail' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AgingBucketDetail)],
      [],
    ),
  'getAllBalances' : IDL.Func([], [IDL.Vec(StudentBalance)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectionSummary' : IDL.Func([], [CollectionSummary], ['query']),
  'getCollectionTrends' : IDL.Func([], [CollectionTrends], ['query']),
  'getFeeStructure' : IDL.Func(
      [FeeStructureId],
      [IDL.Opt(FeeStructure)],
      ['query'],
    ),
  'getFeeStructureBalances' : IDL.Func(
      [FeeStructureId],
      [IDL.Vec(StudentBalance)],
      ['query'],
    ),
  'getPaymentMethodBreakdown' : IDL.Func(
      [],
      [PaymentMethodBreakdown],
      ['query'],
    ),
  'getPaymentsByDateRange' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentBalances' : IDL.Func(
      [StudentId],
      [IDL.Vec(StudentBalance)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFeeStructures' : IDL.Func([], [IDL.Vec(FeeStructure)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listStudentsByGroup' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'recordPayment' : IDL.Func(
      [RecordPaymentInput],
      [IDL.Variant({ 'ok' : Payment, 'err' : RecordPaymentError })],
      [],
    ),
  'unenrollStudent' : IDL.Func([StudentId, FeeStructureId], [IDL.Bool], []),
  'updateFeeStructure' : IDL.Func(
      [UpdateFeeStructureInput],
      [IDL.Opt(FeeStructure)],
      [],
    ),
  'updateOverdueStatuses' : IDL.Func([], [], []),
  'updateStudent' : IDL.Func([UpdateStudentInput], [IDL.Opt(Student)], []),
  'waiveFee' : IDL.Func(
      [StudentId, FeeStructureId, IDL.Text],
      [IDL.Opt(FeeAssignment)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FeeStructureId = IDL.Nat;
  const AssignmentId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
    'waived' : IDL.Null,
    'partial' : IDL.Null,
  });
  const StudentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const FeeAssignment = IDL.Record({
    'id' : AssignmentId,
    'status' : PaymentStatus,
    'studentId' : StudentId,
    'feeStructureId' : FeeStructureId,
    'assignedAt' : Timestamp,
    'waivedReason' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
  });
  const CsvStudentRow = IDL.Record({
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'group' : IDL.Text,
  });
  const ImportRowError = IDL.Record({
    'row' : IDL.Nat,
    'field' : IDL.Text,
    'value' : IDL.Text,
    'message' : IDL.Text,
  });
  const ImportResult = IDL.Record({
    'imported' : IDL.Nat,
    'errors' : IDL.Vec(ImportRowError),
  });
  const FeePeriod = IDL.Variant({
    'semester' : IDL.Null,
    'term' : IDL.Null,
    'annual' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const LatePenalty = IDL.Variant({
    'fixed' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const CreateFeeStructureInput = IDL.Record({
    'endDate' : Timestamp,
    'period' : FeePeriod,
    'name' : IDL.Text,
    'latePenalty' : IDL.Opt(LatePenalty),
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
    'startDate' : Timestamp,
  });
  const FeeStructure = IDL.Record({
    'id' : FeeStructureId,
    'endDate' : Timestamp,
    'period' : FeePeriod,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'latePenalty' : IDL.Opt(LatePenalty),
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'amount' : IDL.Nat,
    'startDate' : Timestamp,
  });
  const CreateStudentInput = IDL.Record({
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'group' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'group' : IDL.Text,
  });
  const AgingBucket = IDL.Record({
    'count' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'bucket' : IDL.Text,
  });
  const AgingBucketDetail = IDL.Record({
    'daysOverdue' : IDL.Nat,
    'feeStructureName' : IDL.Text,
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'amountPaid' : IDL.Nat,
    'amountDue' : IDL.Nat,
  });
  const StudentBalance = IDL.Record({
    'status' : PaymentStatus,
    'feeStructureName' : IDL.Text,
    'studentId' : StudentId,
    'feeStructureId' : FeeStructureId,
    'studentName' : IDL.Text,
    'penaltyAmount' : IDL.Nat,
    'dueDate' : Timestamp,
    'totalAmount' : IDL.Nat,
    'outstandingAmount' : IDL.Nat,
    'totalWithPenalty' : IDL.Nat,
    'paidAmount' : IDL.Nat,
  });
  const CollectionSummary = IDL.Record({
    'totalOverdue' : IDL.Nat,
    'totalCollected' : IDL.Nat,
    'totalOutstanding' : IDL.Nat,
    'totalWaived' : IDL.Nat,
    'totalOutstandingWithPenalty' : IDL.Nat,
    'paymentCount' : IDL.Nat,
  });
  const CollectionTrends = IDL.Record({
    'previousPeriodTotal' : IDL.Nat,
    'previousPeriodCount' : IDL.Nat,
    'currentPeriodTotal' : IDL.Nat,
    'currentPeriodCount' : IDL.Nat,
  });
  const PaymentMethodBreakdown = IDL.Record({
    'cash' : IDL.Nat,
    'check' : IDL.Nat,
    'transfer' : IDL.Nat,
    'online' : IDL.Nat,
  });
  const PaymentId = IDL.Nat;
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'check' : IDL.Null,
    'transfer' : IDL.Null,
    'online' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'method' : PaymentMethod,
    'studentId' : StudentId,
    'feeStructureId' : FeeStructureId,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const RecordPaymentInput = IDL.Record({
    'method' : PaymentMethod,
    'studentId' : StudentId,
    'feeStructureId' : FeeStructureId,
    'date' : Timestamp,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const RecordPaymentError = IDL.Variant({
    'DuplicateReceipt' : IDL.Null,
    'NotFound' : IDL.Null,
  });
  const UpdateFeeStructureInput = IDL.Record({
    'id' : FeeStructureId,
    'endDate' : Timestamp,
    'period' : FeePeriod,
    'name' : IDL.Text,
    'latePenalty' : IDL.Opt(LatePenalty),
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
    'startDate' : Timestamp,
  });
  const UpdateStudentInput = IDL.Record({
    'id' : StudentId,
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'group' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignFeeToGroup' : IDL.Func(
        [IDL.Text, FeeStructureId],
        [IDL.Vec(FeeAssignment)],
        [],
      ),
    'assignFeeToStudent' : IDL.Func(
        [StudentId, FeeStructureId],
        [FeeAssignment],
        [],
      ),
    'bulkImportStudents' : IDL.Func(
        [IDL.Vec(CsvStudentRow)],
        [ImportResult],
        [],
      ),
    'checkReceiptExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createFeeStructure' : IDL.Func(
        [CreateFeeStructureInput],
        [FeeStructure],
        [],
      ),
    'createStudent' : IDL.Func([CreateStudentInput], [Student], []),
    'deleteFeeStructure' : IDL.Func([FeeStructureId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'duplicateFeeStructure' : IDL.Func(
        [FeeStructureId],
        [IDL.Opt(FeeStructure)],
        [],
      ),
    'getAgingReport' : IDL.Func([], [IDL.Vec(AgingBucket)], []),
    'getAgingReportDetail' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AgingBucketDetail)],
        [],
      ),
    'getAllBalances' : IDL.Func([], [IDL.Vec(StudentBalance)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectionSummary' : IDL.Func([], [CollectionSummary], ['query']),
    'getCollectionTrends' : IDL.Func([], [CollectionTrends], ['query']),
    'getFeeStructure' : IDL.Func(
        [FeeStructureId],
        [IDL.Opt(FeeStructure)],
        ['query'],
      ),
    'getFeeStructureBalances' : IDL.Func(
        [FeeStructureId],
        [IDL.Vec(StudentBalance)],
        ['query'],
      ),
    'getPaymentMethodBreakdown' : IDL.Func(
        [],
        [PaymentMethodBreakdown],
        ['query'],
      ),
    'getPaymentsByDateRange' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentBalances' : IDL.Func(
        [StudentId],
        [IDL.Vec(StudentBalance)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFeeStructures' : IDL.Func([], [IDL.Vec(FeeStructure)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listStudentsByGroup' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'recordPayment' : IDL.Func(
        [RecordPaymentInput],
        [IDL.Variant({ 'ok' : Payment, 'err' : RecordPaymentError })],
        [],
      ),
    'unenrollStudent' : IDL.Func([StudentId, FeeStructureId], [IDL.Bool], []),
    'updateFeeStructure' : IDL.Func(
        [UpdateFeeStructureInput],
        [IDL.Opt(FeeStructure)],
        [],
      ),
    'updateOverdueStatuses' : IDL.Func([], [], []),
    'updateStudent' : IDL.Func([UpdateStudentInput], [IDL.Opt(Student)], []),
    'waiveFee' : IDL.Func(
        [StudentId, FeeStructureId, IDL.Text],
        [IDL.Opt(FeeAssignment)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };