/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateFeeStructureInput {
    endDate: Timestamp;
    period: FeePeriod;
    name: string;
    latePenalty?: LatePenalty;
    dueDate: Timestamp;
    description: string;
    amount: bigint;
    startDate: Timestamp;
}
export type Timestamp = bigint;
export interface RecordPaymentInput {
    method: PaymentMethod;
    studentId: StudentId;
    feeStructureId: FeeStructureId;
    date: Timestamp;
    notes: string;
    amount: bigint;
    receiptNumber: string;
}
export interface StudentBalance {
    status: PaymentStatus;
    feeStructureName: string;
    studentId: StudentId;
    feeStructureId: FeeStructureId;
    studentName: string;
    dueDate: Timestamp;
    totalAmount: bigint;
    outstandingAmount: bigint;
    paidAmount: bigint;
}
export interface PaymentMethodBreakdown {
    cash: bigint;
    check: bigint;
    transfer: bigint;
    online: bigint;
}
export interface UpdateFeeStructureInput {
    id: FeeStructureId;
    endDate: Timestamp;
    period: FeePeriod;
    name: string;
    latePenalty?: LatePenalty;
    dueDate: Timestamp;
    description: string;
    amount: bigint;
    startDate: Timestamp;
}
export type FeeStructureId = bigint;
export interface Payment {
    id: PaymentId;
    method: PaymentMethod;
    studentId: StudentId;
    feeStructureId: FeeStructureId;
    date: Timestamp;
    createdAt: Timestamp;
    notes: string;
    amount: bigint;
    receiptNumber: string;
}
export interface CsvStudentRow {
    studentId: string;
    name: string;
    email: string;
    group: string;
}
export type StudentId = bigint;
export interface UpdateStudentInput {
    id: StudentId;
    studentId: string;
    name: string;
    email: string;
    group: string;
}
export interface FeeStructure {
    id: FeeStructureId;
    endDate: Timestamp;
    period: FeePeriod;
    name: string;
    createdAt: Timestamp;
    latePenalty?: LatePenalty;
    dueDate: Timestamp;
    description: string;
    updatedAt: Timestamp;
    amount: bigint;
    startDate: Timestamp;
}
export interface CreateStudentInput {
    studentId: string;
    name: string;
    email: string;
    group: string;
}
export interface CollectionSummary {
    totalOverdue: bigint;
    totalCollected: bigint;
    totalOutstanding: bigint;
    totalWaived: bigint;
    paymentCount: bigint;
}
export interface AgingBucket {
    count: bigint;
    totalAmount: bigint;
    bucket: string;
}
export type LatePenalty = {
    __kind__: "fixed";
    fixed: bigint;
} | {
    __kind__: "percentage";
    percentage: bigint;
};
export type PaymentId = bigint;
export type AssignmentId = bigint;
export interface FeeAssignment {
    id: AssignmentId;
    status: PaymentStatus;
    studentId: StudentId;
    feeStructureId: FeeStructureId;
    assignedAt: Timestamp;
    waivedReason?: string;
    updatedAt: Timestamp;
}
export interface Student {
    id: StudentId;
    studentId: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    group: string;
}
export enum FeePeriod {
    semester = "semester",
    term = "term",
    annual = "annual",
    monthly = "monthly"
}
export enum PaymentMethod {
    cash = "cash",
    check = "check",
    transfer = "transfer",
    online = "online"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    overdue = "overdue",
    waived = "waived",
    partial = "partial"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignFeeToGroup(group: string, feeStructureId: FeeStructureId): Promise<Array<FeeAssignment>>;
    assignFeeToStudent(studentId: StudentId, feeStructureId: FeeStructureId): Promise<FeeAssignment>;
    bulkImportStudents(rows: Array<CsvStudentRow>): Promise<Array<Student>>;
    createFeeStructure(input: CreateFeeStructureInput): Promise<FeeStructure>;
    createStudent(input: CreateStudentInput): Promise<Student>;
    deleteFeeStructure(id: FeeStructureId): Promise<boolean>;
    deleteStudent(id: StudentId): Promise<boolean>;
    duplicateFeeStructure(id: FeeStructureId): Promise<FeeStructure | null>;
    getAgingReport(): Promise<Array<AgingBucket>>;
    getAllBalances(): Promise<Array<StudentBalance>>;
    getCallerUserRole(): Promise<UserRole>;
    getCollectionSummary(): Promise<CollectionSummary>;
    getFeeStructure(id: FeeStructureId): Promise<FeeStructure | null>;
    getFeeStructureBalances(feeStructureId: FeeStructureId): Promise<Array<StudentBalance>>;
    getPaymentMethodBreakdown(): Promise<PaymentMethodBreakdown>;
    getPaymentsByDateRange(fromDate: Timestamp, toDate: Timestamp): Promise<Array<Payment>>;
    getStudent(id: StudentId): Promise<Student | null>;
    getStudentBalances(studentId: StudentId): Promise<Array<StudentBalance>>;
    isCallerAdmin(): Promise<boolean>;
    listFeeStructures(): Promise<Array<FeeStructure>>;
    listStudents(): Promise<Array<Student>>;
    listStudentsByGroup(group: string): Promise<Array<Student>>;
    recordPayment(input: RecordPaymentInput): Promise<Payment>;
    unenrollStudent(studentId: StudentId, feeStructureId: FeeStructureId): Promise<boolean>;
    updateFeeStructure(input: UpdateFeeStructureInput): Promise<FeeStructure | null>;
    updateOverdueStatuses(): Promise<void>;
    updateStudent(input: UpdateStudentInput): Promise<Student | null>;
    waiveFee(studentId: StudentId, feeStructureId: FeeStructureId, reason: string): Promise<FeeAssignment | null>;
}
import type { AssignmentId as _AssignmentId, CreateFeeStructureInput as _CreateFeeStructureInput, FeeAssignment as _FeeAssignment, FeePeriod as _FeePeriod, FeeStructure as _FeeStructure, FeeStructureId as _FeeStructureId, LatePenalty as _LatePenalty, Payment as _Payment, PaymentId as _PaymentId, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, RecordPaymentInput as _RecordPaymentInput, Student as _Student, StudentBalance as _StudentBalance, StudentId as _StudentId, Timestamp as _Timestamp, UpdateFeeStructureInput as _UpdateFeeStructureInput, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignFeeToGroup(arg0: string, arg1: FeeStructureId): Promise<Array<FeeAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.assignFeeToGroup(arg0, arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignFeeToGroup(arg0, arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignFeeToStudent(arg0: StudentId, arg1: FeeStructureId): Promise<FeeAssignment> {
        if (this.processError) {
            try {
                const result = await this.actor.assignFeeToStudent(arg0, arg1);
                return from_candid_FeeAssignment_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignFeeToStudent(arg0, arg1);
            return from_candid_FeeAssignment_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkImportStudents(arg0: Array<CsvStudentRow>): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportStudents(arg0);
            return result;
        }
    }
    async createFeeStructure(arg0: CreateFeeStructureInput): Promise<FeeStructure> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeeStructure(to_candid_CreateFeeStructureInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FeeStructure_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeeStructure(to_candid_CreateFeeStructureInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FeeStructure_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: CreateStudentInput): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0);
            return result;
        }
    }
    async deleteFeeStructure(arg0: FeeStructureId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeeStructure(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeeStructure(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async duplicateFeeStructure(arg0: FeeStructureId): Promise<FeeStructure | null> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateFeeStructure(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateFeeStructure(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgingReport(): Promise<Array<AgingBucket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgingReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgingReport();
            return result;
        }
    }
    async getAllBalances(): Promise<Array<StudentBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBalances();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBalances();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionSummary(): Promise<CollectionSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionSummary();
            return result;
        }
    }
    async getFeeStructure(arg0: FeeStructureId): Promise<FeeStructure | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStructure(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStructure(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeStructureBalances(arg0: FeeStructureId): Promise<Array<StudentBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStructureBalances(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStructureBalances(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentMethodBreakdown(): Promise<PaymentMethodBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentMethodBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentMethodBreakdown();
            return result;
        }
    }
    async getPaymentsByDateRange(arg0: Timestamp, arg1: Timestamp): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByDateRange(arg0, arg1);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByDateRange(arg0, arg1);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentBalances(arg0: StudentId): Promise<Array<StudentBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentBalances(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentBalances(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFeeStructures(): Promise<Array<FeeStructure>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeeStructures();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeeStructures();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return result;
        }
    }
    async listStudentsByGroup(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudentsByGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudentsByGroup(arg0);
            return result;
        }
    }
    async recordPayment(arg0: RecordPaymentInput): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(to_candid_RecordPaymentInput_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Payment_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(to_candid_RecordPaymentInput_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Payment_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async unenrollStudent(arg0: StudentId, arg1: FeeStructureId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unenrollStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unenrollStudent(arg0, arg1);
            return result;
        }
    }
    async updateFeeStructure(arg0: UpdateFeeStructureInput): Promise<FeeStructure | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeeStructure(to_candid_UpdateFeeStructureInput_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeeStructure(to_candid_UpdateFeeStructureInput_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOverdueStatuses(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOverdueStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOverdueStatuses();
            return result;
        }
    }
    async updateStudent(arg0: UpdateStudentInput): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async waiveFee(arg0: StudentId, arg1: FeeStructureId, arg2: string): Promise<FeeAssignment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.waiveFee(arg0, arg1, arg2);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.waiveFee(arg0, arg1, arg2);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_FeeAssignment_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeAssignment): FeeAssignment {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FeePeriod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeePeriod): FeePeriod {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FeeStructure_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeStructure): FeeStructure {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_LatePenalty_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LatePenalty): LatePenalty {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_StudentBalance_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentBalance): StudentBalance {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LatePenalty]): LatePenalty | null {
    return value.length === 0 ? null : from_candid_LatePenalty_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeeStructure]): FeeStructure | null {
    return value.length === 0 ? null : from_candid_FeeStructure_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeeAssignment]): FeeAssignment | null {
    return value.length === 0 ? null : from_candid_FeeAssignment_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FeeStructureId;
    endDate: _Timestamp;
    period: _FeePeriod;
    name: string;
    createdAt: _Timestamp;
    latePenalty: [] | [_LatePenalty];
    dueDate: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    amount: bigint;
    startDate: _Timestamp;
}): {
    id: FeeStructureId;
    endDate: Timestamp;
    period: FeePeriod;
    name: string;
    createdAt: Timestamp;
    latePenalty?: LatePenalty;
    dueDate: Timestamp;
    description: string;
    updatedAt: Timestamp;
    amount: bigint;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        endDate: value.endDate,
        period: from_candid_FeePeriod_n17(_uploadFile, _downloadFile, value.period),
        name: value.name,
        createdAt: value.createdAt,
        latePenalty: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.latePenalty)),
        dueDate: value.dueDate,
        description: value.description,
        updatedAt: value.updatedAt,
        amount: value.amount,
        startDate: value.startDate
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    feeStructureName: string;
    studentId: _StudentId;
    feeStructureId: _FeeStructureId;
    studentName: string;
    dueDate: _Timestamp;
    totalAmount: bigint;
    outstandingAmount: bigint;
    paidAmount: bigint;
}): {
    status: PaymentStatus;
    feeStructureName: string;
    studentId: StudentId;
    feeStructureId: FeeStructureId;
    studentName: string;
    dueDate: Timestamp;
    totalAmount: bigint;
    outstandingAmount: bigint;
    paidAmount: bigint;
} {
    return {
        status: from_candid_PaymentStatus_n6(_uploadFile, _downloadFile, value.status),
        feeStructureName: value.feeStructureName,
        studentId: value.studentId,
        feeStructureId: value.feeStructureId,
        studentName: value.studentName,
        dueDate: value.dueDate,
        totalAmount: value.totalAmount,
        outstandingAmount: value.outstandingAmount,
        paidAmount: value.paidAmount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    method: _PaymentMethod;
    studentId: _StudentId;
    feeStructureId: _FeeStructureId;
    date: _Timestamp;
    createdAt: _Timestamp;
    notes: string;
    amount: bigint;
    receiptNumber: string;
}): {
    id: PaymentId;
    method: PaymentMethod;
    studentId: StudentId;
    feeStructureId: FeeStructureId;
    date: Timestamp;
    createdAt: Timestamp;
    notes: string;
    amount: bigint;
    receiptNumber: string;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n31(_uploadFile, _downloadFile, value.method),
        studentId: value.studentId,
        feeStructureId: value.feeStructureId,
        date: value.date,
        createdAt: value.createdAt,
        notes: value.notes,
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssignmentId;
    status: _PaymentStatus;
    studentId: _StudentId;
    feeStructureId: _FeeStructureId;
    assignedAt: _Timestamp;
    waivedReason: [] | [string];
    updatedAt: _Timestamp;
}): {
    id: AssignmentId;
    status: PaymentStatus;
    studentId: StudentId;
    feeStructureId: FeeStructureId;
    assignedAt: Timestamp;
    waivedReason?: string;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n6(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        feeStructureId: value.feeStructureId,
        assignedAt: value.assignedAt,
        waivedReason: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.waivedReason)),
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    semester: null;
} | {
    term: null;
} | {
    annual: null;
} | {
    monthly: null;
}): FeePeriod {
    return "semester" in value ? FeePeriod.semester : "term" in value ? FeePeriod.term : "annual" in value ? FeePeriod.annual : "monthly" in value ? FeePeriod.monthly : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: bigint;
} | {
    percentage: bigint;
}): {
    __kind__: "fixed";
    fixed: bigint;
} | {
    __kind__: "percentage";
    percentage: bigint;
} {
    return "fixed" in value ? {
        __kind__: "fixed",
        fixed: value.fixed
    } : "percentage" in value ? {
        __kind__: "percentage",
        percentage: value.percentage
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    check: null;
} | {
    transfer: null;
} | {
    online: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "check" in value ? PaymentMethod.check : "transfer" in value ? PaymentMethod.transfer : "online" in value ? PaymentMethod.online : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
} | {
    waived: null;
} | {
    partial: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "overdue" in value ? PaymentStatus.overdue : "waived" in value ? PaymentStatus.waived : "partial" in value ? PaymentStatus.partial : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentBalance>): Array<StudentBalance> {
    return value.map((x)=>from_candid_StudentBalance_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeAssignment>): Array<FeeAssignment> {
    return value.map((x)=>from_candid_FeeAssignment_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeStructure>): Array<FeeStructure> {
    return value.map((x)=>from_candid_FeeStructure_n15(_uploadFile, _downloadFile, x));
}
function to_candid_CreateFeeStructureInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFeeStructureInput): _CreateFeeStructureInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_FeePeriod_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeePeriod): _FeePeriod {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_LatePenalty_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LatePenalty): _LatePenalty {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_RecordPaymentInput_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordPaymentInput): _RecordPaymentInput {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFeeStructureInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFeeStructureInput): _UpdateFeeStructureInput {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: Timestamp;
    period: FeePeriod;
    name: string;
    latePenalty?: LatePenalty;
    dueDate: Timestamp;
    description: string;
    amount: bigint;
    startDate: Timestamp;
}): {
    endDate: _Timestamp;
    period: _FeePeriod;
    name: string;
    latePenalty: [] | [_LatePenalty];
    dueDate: _Timestamp;
    description: string;
    amount: bigint;
    startDate: _Timestamp;
} {
    return {
        endDate: value.endDate,
        period: to_candid_FeePeriod_n11(_uploadFile, _downloadFile, value.period),
        name: value.name,
        latePenalty: value.latePenalty ? candid_some(to_candid_LatePenalty_n13(_uploadFile, _downloadFile, value.latePenalty)) : candid_none(),
        dueDate: value.dueDate,
        description: value.description,
        amount: value.amount,
        startDate: value.startDate
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: PaymentMethod;
    studentId: StudentId;
    feeStructureId: FeeStructureId;
    date: Timestamp;
    notes: string;
    amount: bigint;
    receiptNumber: string;
}): {
    method: _PaymentMethod;
    studentId: _StudentId;
    feeStructureId: _FeeStructureId;
    date: _Timestamp;
    notes: string;
    amount: bigint;
    receiptNumber: string;
} {
    return {
        method: to_candid_PaymentMethod_n37(_uploadFile, _downloadFile, value.method),
        studentId: value.studentId,
        feeStructureId: value.feeStructureId,
        date: value.date,
        notes: value.notes,
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: FeeStructureId;
    endDate: Timestamp;
    period: FeePeriod;
    name: string;
    latePenalty?: LatePenalty;
    dueDate: Timestamp;
    description: string;
    amount: bigint;
    startDate: Timestamp;
}): {
    id: _FeeStructureId;
    endDate: _Timestamp;
    period: _FeePeriod;
    name: string;
    latePenalty: [] | [_LatePenalty];
    dueDate: _Timestamp;
    description: string;
    amount: bigint;
    startDate: _Timestamp;
} {
    return {
        id: value.id,
        endDate: value.endDate,
        period: to_candid_FeePeriod_n11(_uploadFile, _downloadFile, value.period),
        name: value.name,
        latePenalty: value.latePenalty ? candid_some(to_candid_LatePenalty_n13(_uploadFile, _downloadFile, value.latePenalty)) : candid_none(),
        dueDate: value.dueDate,
        description: value.description,
        amount: value.amount,
        startDate: value.startDate
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeePeriod): {
    semester: null;
} | {
    term: null;
} | {
    annual: null;
} | {
    monthly: null;
} {
    return value == FeePeriod.semester ? {
        semester: null
    } : value == FeePeriod.term ? {
        term: null
    } : value == FeePeriod.annual ? {
        annual: null
    } : value == FeePeriod.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "fixed";
    fixed: bigint;
} | {
    __kind__: "percentage";
    percentage: bigint;
}): {
    fixed: bigint;
} | {
    percentage: bigint;
} {
    return value.__kind__ === "fixed" ? {
        fixed: value.fixed
    } : value.__kind__ === "percentage" ? {
        percentage: value.percentage
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    check: null;
} | {
    transfer: null;
} | {
    online: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.check ? {
        check: null
    } : value == PaymentMethod.transfer ? {
        transfer: null
    } : value == PaymentMethod.online ? {
        online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
